import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white min-h-screen">
          <div className="max-w-full sm:max-w-md md:max-w-lg lg:max-w-xl xl:max-w-[1536px] ml-auto mr-auto bg-blue-700">{children}</div>
        </div>
      </body>
    </html>
  );
}
